apiVersion: v2
name: blittermib
description: Pixelperfect SNMP MIB browser — self-hostable, browser-based reference tool.
type: application
version: 0.5.8
appVersion: "0.17.4"
home: https://github.com/no42-org/blittermib
sources:
  - https://github.com/no42-org/blittermib
keywords:
  - snmp
  - mib
  - opennms
maintainers:
  - name: Ronny Trommer
    email: ronny@no42.org
